name: DEPLOY FRONT INTO DEV AZURE
on:
  push:
    branches:
      - main

env:
  APP_NAME: front
  REGISTRY_DOMAIN: resourcesRelationnelles.azurecr.io 
  AZURE_USERNAME: githubactions

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: export short sha env
        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: export image name env
        run: echo "IMAGE_NAME=${REGISTRY_DOMAIN}/front:${GITHUB_SHA_SHORT}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: resourcesRelationnelles.azurecr.io
          username: ${AZURE_USERNAME}
          password: ${{ secrets.AZURE_SERVICE_ACCOUNT_KEY }}
      
      - name: docker build
        run: docker build -t ${IMAGE_NAME} -f front.Dockerfile .
        working-directory: ./ReSourcesRelationnelles

      - name: docker push
        run: docker push ${IMAGE_NAME}
