name: DEPLOY FRONT INTO DEV AZURE
on:
  push:
    branches:
      - main

env:
  APP_NAME: front
  REGISTRY_DOMAIN: vikit.azurecr.io
  AZURE_USERNAME: githubactions

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: see directory
        run: ls
        
      - name: change directory to front 
        run: cd ReSourcesRelationnelles
        
      - name: execute tests
        run: yarn test
        
      - name: export short sha env
        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: export image name env
        run: echo "IMAGE_NAME=${REGISTRY_DOMAIN}/${APP_NAME}:${GITHUB_SHA_SHORT}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: vikit.azurecr.io
          username: githubactions
          password: ${{ secrets.AZURE_SERVICE_ACCOUNT_KEY }}

      - name: docker build
        run: docker build -t ${IMAGE_NAME} -f front.dockerfile .
        working-directory: ./ReSourcesRelationnelles

      - name: docker push
        run: docker push ${IMAGE_NAME}
